[package]
name = "fedora-update-feedback"
description = "provide feedback for fedora updates (inspired by fedora-easy-karma)"
license = "MIT OR Apache-2.0"

version = "0.5.1"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["fedora", "bodhi", "updates", "feedback"]
repository = "https://pagure.io/ironthree/fedora-update-feedback"

[dependencies]
bodhi = "^0.5.4"
dirs = "^2.0.2"
rpassword = "^4.0.3"
rustyline = "^6.0.0"
secret-service = "^1.1.0"
serde = { version = "^1.0.104", features = ["derive"] }
structopt = { version = "^0.3.8", features = ["color", "suggestions", "wrap_help"] }
term_size = "^0.3.1"
textwrap = "^0.11.0"
toml = "^0.5.5"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

