[package]
name = "fedora-update-feedback"
description = "provide feedback for fedora updates (inspired by fedora-easy-karma)"
license = "MIT OR Apache-2.0"

version = "0.1.0"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["fedora", "bodhi", "updates", "feedback"]

[features]
default = []
feedback = []

[dependencies]
bodhi = "^0.5.0"
dirs = "^2.0.2"
rpassword = "^4.0.3"
rustyline = "^6.0.0"
serde = { version = "^1.0.104", features = ["derive"] }
toml = "^0.5.5"

[profile.release]
codegen-units = 1
lto = true

